### ISSUE TITLE
Sort'o'matic : error in description vs full information

### ISSUE THREAD

**Issue by Euzebius** [CounterHack/HolidayHack2020#11]
Howdy,

I think there is an error in the description of the second expected regex in this task.
The exercice says "Matches 3 alpha a-z characters ignoring case" and answering to this exact expectation is not working. (Won't spoil here but here's the screen)
![image](https://user-images.githubusercontent.com/18382660/101887393-1600fd80-3b9d-11eb-88f8-18bc33001e4f.png)

I figured out why by clicking on the task description:
![image](https://user-images.githubusercontent.com/18382660/101887518-45176f00-3b9d-11eb-918a-e93ac0a26247.png)

So I guess it would be better to correct the task by saying "3 or more" directly

**Comment by chrisjd20** [comment]
It just says the string has to match 3 characters. 

So:

`abc` would match.

Just as:

`abcd` would match. 

Just as:

`abcde` would match.  

Because in all cases, there is 3 alpha characters for the desired regex to match on. 

If by exact specifications you are thinking the string is comprised of ONLY 3 characters exactly (using anchors), then you would be correct, but the short description and the expanded help don't call for that. It only says it must match 3 alpha characters ignoring case. Keep in mind, there is limited space for a short description. Hence why we added the modal to expand on this for players. As such, the help modals information always takes precedence. 

If you find the short description lacking, always default the the information in the help modal by clicking on the short description.

Otherwise, without seeing your regex, it's hard to know for sure what the disconnect is.

**Comment by Euzebius** [comment]
My regex worked as soon as I updated it to be 3 **or more** chars yesterday. Hint : adding a comma did the thing.

Just wanted to point that it was not really explicit this way and others might find it as an issue. I thought it would be helpful to talk about it. Saying "Matches 3 or more alpha a-z [...]" would have made it easier to understand I guess. But it's probably just me neverwind 😄 

If it's by design then maybe my issue is not really an issue and should be closed.

Sorry for the waste of time on your side.

**Comment by chrisjd20** [comment]
Ok, I hear what your saying. We could probably revisit that question the next time we refine that challenge. I could see how some might draw those conclusions. Thanks for the feedback. :)
