### ISSUE TITLE
elfcode: new lines are being added between functions adding to the overall lines used on level 7

### ISSUE THREAD

**Issue by DigitalSkateboarder** [CounterHack/HolidayHack2020#9]
My code is 50 lines long but when I paste it in, it adds in blank lines which makes my script fail

**Comment by chrisjd20** [comment]
This is by design. we are trying to challenge people to limit the amount of lines they can use and in doing so, write more refined code.  I dont know what your pasting but my guess is the beautifier is expanding it out. 

Try reformatting your code or if you really want to use it, do as one of the elf hints suggests and use a JS minifier:

https://jscompress.com/

**Comment by DigitalSkateboarder** [comment]
All good - many apologies - I was doing an up when I shouldn't have so managed to fit it in

**Comment by chrisjd20** [comment]
No apologies! We value the feedback. And sometimes its easy to get tunnel vision and its nice to ask and have someone unstuck us.
